import type { Metadata } from "next";
import { Playwrite_FR_Moderne } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playwrite = Playwrite_FR_Moderne({
  variable: "--font-playwrite",
  weight: ["100", "200", "300", "400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playwrite.variable} ${playwrite.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
